# Reference config for tg
[general]
time_format = "%A, %e %B %Y %H:%M:%S %Z"

[postgres]
host = "127.0.0.1"
user = "tg"
# password = "some-password"

[markov]
chain_order = 1 # Default order of chains if no order is specified
max_order = 5 # Maximum order

[redis]
address = "127.0.0.1:6379"
# password = "foobar"

#Time in seconds to cache each thing
[cache]
username = 3600
markov_chain = 1300

[disaster]
cooldown = 3 #cooldown time in hours
